name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0, v2.3

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka ordered-set zstandard

    - name: Build EXE with Nuitka (PyQt5)
      shell: cmd
      run: |
        nuitka data_dashboard.py ^
          --standalone ^
          --onefile ^
          --enable-plugin=qt-plugins ^
          --include-qt-plugins=all ^
          --enable-plugin=qt5 ^
          --windows-icon-from-ico=IconD.ico ^
          --output-filename=data-tool.exe

    - name: Upload EXE to release
      uses: softprops/action-gh-release@v1
      with:
        files: data-tool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
