name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'  # Only trigger on version tags like v1.0, v2.3

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka ordered-set zstandard

    - name: Build EXE with Nuitka
      shell: cmd
      run: |
        python -m nuitka data_dashboard.py ^
          --standalone ^
          --onefile ^
          --windows-icon-from-ico=IconD.ico ^
          --output-filename=data-tool.exe ^
          --assume-yes-for-downloads

    - name: Find built executable
      shell: powershell
      run: |
        $exe = Get-ChildItem -Recurse -Name "data-tool.exe" | Select-Object -First 1
        if ($exe) {
          Write-Output "Found executable at: $exe"
          Copy-Item $exe "data-tool.exe"
        } else {
          Write-Error "Executable not found!"
          exit 1
        }

    - name: Upload EXE to release
      uses: softprops/action-gh-release@v2
      with:
        files: data-tool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}